
# SEO
title: Athena Jekyll Theme
description: A simple and elegant theme for Jekyll and GitHub Pages.

# social
social_link: twitter
social_username: broccolini
github_repo: athena # the GitHub repo name for your project
github_username: broccolini
theme_color: light

# Theme
remote_theme: 'broccolini/athena'
remote_theme_layouts: 
  - default
  - page
  - post
  - home
baseurl: '/%name%'

# Stastic UI
social_links:
  - twitter
  - instagram
  - medium
  - dribbble

theme_colors:
  - light
	- black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow


